CREATE TABLE "yields" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"chain" text NOT NULL,
	"project" text NOT NULL,
	"symbol" text NOT NULL,
	"tvl_usd" numeric NOT NULL,
	"apy_base" numeric,
	"apy_reward" numeric,
	"apy" numeric,
	"reward_tokens" text[],
	"pool" uuid,
	"apy_pct_1d" numeric,
	"apy_pct_7d" numeric,
	"apy_pct_30d" numeric,
	"stablecoin" boolean NOT NULL,
	"il_risk" text,
	"exposure" text,
	"predicted_class" text,
	"predicted_probability" numeric,
	"binned_confidence" numeric,
	"pool_meta" text,
	"mu" numeric,
	"sigma" numeric,
	"count" numeric,
	"outlier" boolean NOT NULL,
	"underlying_tokens" text[],
	"il_7d" numeric,
	"apy_base_7d" numeric,
	"apy_mean_30d" numeric,
	"volume_usd_1d" numeric,
	"volume_usd_7d" numeric,
	"apy_base_inception" numeric,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
